---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazonprime
  labels:
    app: amazonprime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazonprime-app
  template:
    metadata:
      labels:
        app: amazonprime-app
    spec:
      containers:
      - name: prime-container
        image: 600627332632.dkr.ecr.eu-north-1.amazonaws.com/amazon-prime:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 3000
...
