name: Deployment to EKS 

on:
  # - push 
  workflow_dispatch
jobs:
  Build-Deploy:     
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1

      - name: AWS EKS credentials
        run: aws eks update-kubeconfig --name devops-project-cluster  --region {{env.AWS_REGION}}# Change to your cluster name

      - name: Update Deployment Image 
        run: |
          sed -i "s/IMAGE_TAG_PLACEHOLDER/${{ github.sha }}/g" ./k8s/app.yaml

      - name: Deploy to EKS
        run: kubectl apply -f k8s_files/  --validate=false 



    
