# name: remote ssh command
# on:
#   push

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@v1.2.1
#         with:
#           host: ${{ secrets.EC2_URL }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
#           script: |
#             echo "Hi there "
name: Remote SSH Command
on:
  push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_URL }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "=== START: Running on EC2 ==="
            echo "Hostname: $(hostname)"
            echo "Current User: $(whoami)"
            echo "Current Directory: $(pwd)"
            echo "Hi there from EC2!"
            echo "=== END: Script Execution ==="
